### PR TITLE
Issues with migrating

### LINKED ISSUE #152: Issues with migrating
I would like to point out that this is not necessarily a bug, but perhaps a thorough explanation is missing from the documentation

I did a pre-test and encounter those issues, it was a clean installation of lisk-core@3.1.0 on ubuntu 20, 
```
lisk-migrator --snapshot-height 20337968 --output ~/.lisk/lisk-core/config/testnet
Verifying if backup height from node config matches snapshot height... Snapshot height matches backup height
Verifying snapshot height to be multiples of round length i.e 103... Snapshot height is valid
Verifying Lisk Core version... 3.1.0 detected
Compiling Lisk Core configuration... done
Loading Lisk Core configuration... done
Creating database instance... done
Creating genesis assets... done
Exporting genesis block to the path /home/lisk-beta/.lisk/lisk-core/config/testnet/15f0dacc1060e91818224a94286b13aa04279c640bd5d6f193182031d133df7c... done
Installing lisk-core v4... done
Creating genesis block... !
Error: Command failed: lisk-core genesis-block:create --network testnet --config=/home/lisk-beta/.lisk/lisk-core/config/testnet/config.json --output=/home/lisk-beta/.lisk/lisk-core/config/testnet/15f0dacc1060e91818224a94286b13aa04279c6400    Error: Lisk validator found 6 error[s]:
    Property '' has extraneous property 'networkVersion'
    Property '' has extraneous property 'label'
    Property '' has extraneous property 'genesisConfig'
    Property '' has extraneous property 'logger'
    Property '' has extraneous property 'forging'
    Property '' has extraneous property 'backup'
    at ChildProcess.exithandler (node:child_process:419:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)
```

if i add --auto-migrate-config, this is the output:

```
lisk-migrator --snapshot-height 20337968 --output ~/.lisk/lisk-core/config/testnet --auto-migrate-config
Verifying if backup height from node config matches snapshot height... Snapshot height matches backup height
Verifying snapshot height to be multiples of round length i.e 103... Snapshot height is valid
Verifying Lisk Core version... 3.1.0 detected
Compiling Lisk Core configuration... done
Loading Lisk Core configuration... done
Creating database instance... done
Creating genesis assets... done
Exporting genesis block to the path /home/lisk-beta/.lisk/lisk-core/config/testnet/15f0dacc1060e91818224a94286b13aa04279c640bd5d6f193182031d133df7c... done
Creating backup for old config... done
Starting migration of custom config properties.... !
TypeError: Cannot read properties of undefined (reading 'version')
    at migrateUserConfig (~/lisk-migrator/dist/utils/config.js:70:26)
    at LiskMigrator.run (~/lisk-migrator/dist/index.js:92:80)
    at async LiskMigrator._run (~/lisk-migrator/node_modules/@oclif/command/lib/command.js:43:20)
```

very confusing with the configs, it seems like there's a conflict with the old/new config.json
also it looks like there's a difference where you run the migrator, i had to go to the `~/.lisk/lisk-core/` folder and run it, otherwise i got
`Error: ENOENT: no such file or directory, open '/home/lisk-beta/lisk-migrator/config/testnet/config.json'`
and all progress was lost at the end without saving the genesis assets.

### PR DESCRIPTION
**Pull request by nagdahimanshu**
### What was the problem?

This PR resolves #152 #135 #160 

### How was it solved?

- [x] Fix logic to resolve config filepath
- [x] Update readme
  - [x] Remove installing migrator from npm section
  - [x] Fix typo
- [x] Updated `SNAPSHOT_TIME_GAP` to `3600`
- [x] Removed support for the `--snapshot-time-gap` flag
- [x] Updated code to install lisk-core v4.0.0-rc.1 and above
- [x] Updated genesisBlockCreateCommand to have the `--export-json` flag enabled
- [x] Updated SDK dependency to v6.0.0-rc.1
- [x] Included zero-balance accounts into the Token sub-store as specified [here](https://github.com/LiskHQ/lips/blob/main/proposals/lip-0063.md#assets-entry-for-token-module) in LIP-0063

### How was it tested?
Local against the testnet and the mainnet

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -124,7 +124,7 @@ class LiskMigrator extends Command {
 			cli.action.start('Verifying if backup height from node config matches snapshot height');
 			if (snapshotHeight !== nodeInfo.backup.height) {
 				this.error(
-					`Snapshot height ${snapshotHeight} does not matches backup height ${nodeInfo.backup.height}.`,
+					`Lisk Core v3 backup height ${nodeInfo.backup.height} does not match the expected snapshot height of ${snapshotHeight}`,
```
Comment (sameersubudhi) [inline src/index.ts:127]:
```suggestion
					`Lisk Core v3 backup height (${nodeInfo.backup.height}) does not match the expected snapshot height (${snapshotHeight}).`,
```

File: test/unit/utils/config.spec.ts [hunk 2]
```diff
@@ -64,3 +69,11 @@ describe('Test resolveConfigPathByNetworkID method', () => {
 		await expect(resolveConfigPathByNetworkID('invalid')).rejects.toThrow();
 	});
 });
+
+describe('Test createBackup method', () => {
+	it('should create backup', async () => {
+		const backupPath = join(__dirname, '../../..', 'backup');
+		await createBackup((configV3 as unknown) as ApplicationConfigV3);
+		expect(fs.existsSync(backupPath)).toBe(true);
```
Comment (sameersubudhi) [inline test/unit/utils/config.spec.ts:77]:
```suggestion
		const expectedBackupPath = join(__dirname, '../../..', 'backup');
		await createBackup((configV3 as unknown) as ApplicationConfigV3);
		expect(fs.existsSync(expectedBackupPath)).toBe(true);
```

**Review by sameersubudhi — CHANGES_REQUESTED** [review]

**Review by priojeetpriyom — APPROVED** [review]

File: test/unit/utils/config.spec.ts [hunk 3]
```diff
@@ -12,21 +12,26 @@
...
 	validateConfig,
 	writeConfig,
 	resolveConfigPathByNetworkID,
+	createBackup,
 } from '../../../src/utils/config';
 import { ApplicationConfigV3 } from '../../../src/types';
 
 describe('Migrate user configuration', () => {
 	const migratedConfigFilePath = `${process.cwd()}/test/config`;
+	const backupPath = join(__dirname, '../../..', 'backup');
```
Comment (sameersubudhi) [inline test/unit/utils/config.spec.ts:29]:
```suggestion
	const expectedBackupPath = join(__dirname, '../../..', 'backup');
```

File: test/unit/utils/config.spec.ts [hunk 4]
```diff
@@ -12,21 +12,26 @@
...
 
-	afterAll(() => fs.removeSync(migratedConfigFilePath));
+	afterAll(() => {
+		fs.removeSync(migratedConfigFilePath);
+		fs.removeSync(backupPath);
```
Comment (sameersubudhi) [inline test/unit/utils/config.spec.ts:33]:
```suggestion
		fs.removeSync(expectedBackupPath);
```

File: test/unit/utils/config.spec.ts [hunk 5]
```diff
@@ -64,3 +69,11 @@ describe('Test resolveConfigPathByNetworkID method', () => {
 		await expect(resolveConfigPathByNetworkID('invalid')).rejects.toThrow();
 	});
 });
+
+describe('Test createBackup method', () => {
+	it('should create backup', async () => {
+		const expectedBackupPath = join(__dirname, '../../..', 'backup');
```
Comment (sameersubudhi) [inline test/unit/utils/config.spec.ts:75]:
```suggestion
```

**Review by sameersubudhi — CHANGES_REQUESTED** [review]

**Review by sergeyshemyakov — APPROVED** [review]
I haven't carefully reviewed all the code refactoring.

**Review by sameersubudhi — APPROVED** [review]

File: src/utils/node.ts [hunk 6]
```diff
@@ -24,7 +24,7 @@ import { Port } from '../types';
 import { getAPIClient } from '../client';
 import { DEFAULT_PORT_P2P, DEFAULT_PORT_RPC } from '../constants';
 
-const INSTALL_LISK_CORE_COMMAND = 'npm i -g lisk-core@^4.0.0-rc.0';
+const INSTALL_LISK_CORE_COMMAND = 'npm i -g lisk-core@^4.0.0-rc.1';
```
Comment (ManuGowda) [inline src/utils/node.ts:27]: you could have taken this as a flag input.. and default it to a specific release, but users can override.. otherwise for release we have keep updating this externally

**Review by ManuGowda — APPROVED** [review]

File: src/utils/node.ts (hunk 6 above)
Comment (sameersubudhi) [reply src/utils/node.ts:27]: The `^` in the code ensures that the latest available version of Lisk Core v4 published to the NPM registry is installed. So, even if we do not update it in the future, it'll work as is.
